# Generated by Django 2.1.2 on 2018-10-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControllerInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_trigger', models.IntegerField(default=0)),
                ('r_trigger', models.IntegerField(default=0)),
                ('l_bump', models.IntegerField(default=0)),
                ('r_bump', models.IntegerField(default=0)),
                ('a', models.IntegerField(default=0)),
                ('b', models.IntegerField(default=0)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('r_stick_x', models.IntegerField(default=0)),
                ('r_stick_y', models.IntegerField(default=0)),
                ('l_stick_x', models.IntegerField(default=0)),
                ('l_stick_y', models.IntegerField(default=0)),
                ('up', models.IntegerField(default=0)),
                ('down', models.IntegerField(default=0)),
                ('left', models.IntegerField(default=0)),
                ('right', models.IntegerField(default=0)),
            ],
        ),
    ]
