# Generated by Django 2.1.2 on 2018-10-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controllerinput',
            name='select',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='controllerinput',
            name='start',
            field=models.IntegerField(default=0),
        ),
    ]
