# Generated by Django 2.1.2 on 2019-01-25 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_auto_20181025_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controllerinput',
            old_name='down',
            new_name='d',
        ),
        migrations.RenameField(
            model_name='controllerinput',
            old_name='left',
            new_name='l',
        ),
        migrations.RenameField(
            model_name='controllerinput',
            old_name='l_bump',
            new_name='lb',
        ),
        migrations.RenameField(
            model_name='controllerinput',
            old_name='l_stick_x',
            new_name='lsx',
        ),
        migrations.RenameField(
            model_name='controllerinput',
            old_name='l_stick_y',
            new_name='lsy',
        ),
        migrations.RenameField(
            model_name='controllerinput',
            old_name='l_trigger',
            new_name='lt',
        ),
        migrations.RenameField(
            model_name='controllerinput',
            old_name='right',
            new_name='r',
        ),
        migrations.RenameField(
            model_name='controllerinput',
            old_name='r_bump',
            new_name='rb',
        ),
        migrations.RenameField(
            model_name='controllerinput',
            old_name='r_stick_x',
            new_name='rsx',
        ),
        migrations.RenameField(
            model_name='controllerinput',
            old_name='r_stick_y',
            new_name='rsy',
        ),
        migrations.RenameField(
            model_name='controllerinput',
            old_name='r_trigger',
            new_name='rt',
        ),
        migrations.RenameField(
            model_name='controllerinput',
            old_name='select',
            new_name='se',
        ),
        migrations.RenameField(
            model_name='controllerinput',
            old_name='start',
            new_name='st',
        ),
        migrations.RenameField(
            model_name='controllerinput',
            old_name='up',
            new_name='u',
        ),
    ]
