# Generated by Django 2.1.2 on 2019-04-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_auto_20190125_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='controllerinput',
            name='hl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='controllerinput',
            name='lim',
            field=models.IntegerField(default=50),
        ),
    ]
