# Generated by Django 2.1.2 on 2018-10-04 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controllerinput',
            name='xButton',
        ),
        migrations.AddField(
            model_name='controllerinput',
            name='a',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='controllerinput',
            name='b',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='controllerinput',
            name='down',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='controllerinput',
            name='l_bump',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='controllerinput',
            name='l_stick_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='controllerinput',
            name='l_stick_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='controllerinput',
            name='l_trigger',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='controllerinput',
            name='left',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='controllerinput',
            name='r_bump',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='controllerinput',
            name='r_stick_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='controllerinput',
            name='r_stick_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='controllerinput',
            name='r_trigger',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='controllerinput',
            name='right',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='controllerinput',
            name='up',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='controllerinput',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='controllerinput',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
