# Generated by Django 2.1.2 on 2019-04-05 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameraIP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cameraip',
            old_name='cameraIP',
            new_name='cameraIPstr',
        ),
    ]
