# Generated by Django 2.1.2 on 2019-02-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='db',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='df',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='dl',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='dr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='qbl',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='qbr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='qfl',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='qfr',
            field=models.IntegerField(default=0),
        ),
    ]
