# Generated by Django 2.1.2 on 2019-03-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_auto_20190209_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='db',
            new_name='da',
        ),
        migrations.RenameField(
            model_name='sensordata',
            old_name='df',
            new_name='dfl',
        ),
        migrations.RenameField(
            model_name='sensordata',
            old_name='dl',
            new_name='dfr',
        ),
        migrations.RenameField(
            model_name='sensordata',
            old_name='dr',
            new_name='dsl',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='dsr',
            field=models.IntegerField(default=0),
        ),
    ]
