# Generated by Django 2.1.2 on 2019-04-25 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_auto_20190318_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='da',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='qbl',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='qbr',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='qfl',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='qfr',
        ),
    ]
